import type { LoadFactor, Part, RoomType } from "@/types/hvac";

export const LOAD_FACTORS: Record<RoomType, LoadFactor> = {
  master_bedroom: { btu: 18, cfm: 1.0, reg: 2 },
  bedroom:        { btu: 18, cfm: 1.0, reg: 1 },
  living_room:    { btu: 22, cfm: 1.2, reg: 2 },
  family_room:    { btu: 22, cfm: 1.2, reg: 2 },
  kitchen:        { btu: 26, cfm: 1.3, reg: 1 },
  dining_room:    { btu: 20, cfm: 1.0, reg: 1 },
  bathroom:       { btu: 20, cfm: 0.8, reg: 1 },
  half_bath:      { btu: 20, cfm: 0.8, reg: 0 },
  hallway:        { btu: 14, cfm: 0.5, reg: 1 },
  laundry:        { btu: 20, cfm: 0.8, reg: 1 },
  office:         { btu: 20, cfm: 1.0, reg: 1 },
  foyer:          { btu: 18, cfm: 0.6, reg: 1 },
  sunroom:        { btu: 35, cfm: 1.5, reg: 2 },
  bonus_room:     { btu: 22, cfm: 1.0, reg: 1 },
  basement:       { btu: 14, cfm: 0.8, reg: 1 },
  closet:         { btu: 0,  cfm: 0,   reg: 0 },
  garage:         { btu: 0,  cfm: 0,   reg: 0 },
};

export const ROOM_TYPES: RoomType[] = Object.keys(LOAD_FACTORS) as RoomType[];

export const PARTS_DB: Record<string, Part> = {
  "COND-2T-14S":   { name: "2-Ton Condenser (14 SEER2)",        category: "Major Equipment",       unit: "ea", price: 1850,  supplier: "Carrier",            sku: "24ACC636A003"  },
  "COND-2.5T-14S": { name: "2.5-Ton Condenser (14 SEER2)",      category: "Major Equipment",       unit: "ea", price: 2150,  supplier: "Carrier",            sku: "24ACC660A003"  },
  "COND-3T-14S":   { name: "3-Ton Condenser (14 SEER2)",        category: "Major Equipment",       unit: "ea", price: 2450,  supplier: "Carrier",            sku: "24ACC636A003"  },
  "COND-3.5T-16S": { name: "3.5-Ton Condenser (16 SEER2)",      category: "Major Equipment",       unit: "ea", price: 2950,  supplier: "Carrier",            sku: "24ACC642A003"  },
  "COND-4T-16S":   { name: "4-Ton Condenser (16 SEER2)",        category: "Major Equipment",       unit: "ea", price: 3350,  supplier: "Carrier",            sku: "24ACC648A003"  },
  "COND-5T-16S":   { name: "5-Ton Condenser (16 SEER2)",        category: "Major Equipment",       unit: "ea", price: 3950,  supplier: "Carrier",            sku: "24ACC660A003"  },
  "AH-2T-VS":      { name: "2-Ton Air Handler (Var Speed)",      category: "Major Equipment",       unit: "ea", price: 1250,  supplier: "Carrier",            sku: "FE4ANB002"     },
  "AH-2.5T-VS":    { name: "2.5-Ton Air Handler (Var Speed)",    category: "Major Equipment",       unit: "ea", price: 1400,  supplier: "Carrier",            sku: "FE4ANB0025"    },
  "AH-3T-VS":      { name: "3-Ton Air Handler (Var Speed)",      category: "Major Equipment",       unit: "ea", price: 1550,  supplier: "Carrier",            sku: "FE4ANB003"     },
  "AH-3.5T-VS":    { name: "3.5-Ton Air Handler (Var Speed)",    category: "Major Equipment",       unit: "ea", price: 1700,  supplier: "Carrier",            sku: "FE4ANB0035"    },
  "AH-4T-VS":      { name: "4-Ton Air Handler (Var Speed)",      category: "Major Equipment",       unit: "ea", price: 1850,  supplier: "Carrier",            sku: "FE4ANB004"     },
  "AH-5T-VS":      { name: "5-Ton Air Handler (Var Speed)",      category: "Major Equipment",       unit: "ea", price: 2150,  supplier: "Carrier",            sku: "FE4ANB005"     },
  "TSTAT-WIFI":    { name: "Wi-Fi Smart Thermostat",             category: "Controls",              unit: "ea", price: 165,   supplier: "Ecobee",             sku: "EB-STATEsi"    },
  "TRUNK-8x12":    { name: "8\"x12\" Sheet Metal Trunk",         category: "Ductwork",              unit: "ft", price: 12.50, supplier: "Local Sheet Metal",  sku: "SM0812"        },
  "TRUNK-10x14":   { name: "10\"x14\" Sheet Metal Trunk",        category: "Ductwork",              unit: "ft", price: 15.75, supplier: "Local Sheet Metal",  sku: "SM1014"        },
  "TRUNK-12x16":   { name: "12\"x16\" Sheet Metal Trunk",        category: "Ductwork",              unit: "ft", price: 18.50, supplier: "Local Sheet Metal",  sku: "SM1216"        },
  "FLEX-6":        { name: "6\" Round Flex Duct",                category: "Ductwork",              unit: "ft", price: 2.85,  supplier: "Hart & Cooley",      sku: "FD06"          },
  "FLEX-8":        { name: "8\" Round Flex Duct",                category: "Ductwork",              unit: "ft", price: 3.45,  supplier: "Hart & Cooley",      sku: "FD08"          },
  "FLEX-10":       { name: "10\" Round Flex Duct",               category: "Ductwork",              unit: "ft", price: 4.25,  supplier: "Hart & Cooley",      sku: "FD10"          },
  "PLENUM-SUP":    { name: "Supply Plenum",                      category: "Ductwork",              unit: "ea", price: 145,   supplier: "Local Sheet Metal",  sku: "PL-SUP"        },
  "PLENUM-RET":    { name: "Return Plenum",                      category: "Ductwork",              unit: "ea", price: 165,   supplier: "Local Sheet Metal",  sku: "PL-RET"        },
  "REG-4x12":      { name: "4\"x12\" Supply Register",           category: "Registers & Grilles",   unit: "ea", price: 9.75,  supplier: "Hart & Cooley",      sku: "421-4x12W"     },
  "REG-6x12":      { name: "6\"x12\" Supply Register",           category: "Registers & Grilles",   unit: "ea", price: 12.50, supplier: "Hart & Cooley",      sku: "421-6x12W"     },
  "RET-20x25":     { name: "20\"x25\" Return Grille",            category: "Registers & Grilles",   unit: "ea", price: 22.50, supplier: "Hart & Cooley",      sku: "RG-2025W"      },
  "RET-20x30":     { name: "20\"x30\" Return Grille",            category: "Registers & Grilles",   unit: "ea", price: 28,    supplier: "Hart & Cooley",      sku: "RG-2030W"      },
  "RET-24x30":     { name: "24\"x30\" Return Grille",            category: "Registers & Grilles",   unit: "ea", price: 34,    supplier: "Hart & Cooley",      sku: "RG-2430W"      },
  "LS-25":         { name: "3/8\"x3/4\" Line Set (25ft)",        category: "Refrigerant & Lines",   unit: "ea", price: 85,    supplier: "Mueller",            sku: "LS-3825"       },
  "LS-50":         { name: "3/8\"x3/4\" Line Set (50ft)",        category: "Refrigerant & Lines",   unit: "ea", price: 145,   supplier: "Mueller",            sku: "LS-3850"       },
  "R410A-25":      { name: "R-410A Refrigerant (25lb)",          category: "Refrigerant & Lines",   unit: "ea", price: 185,   supplier: "National",           sku: "R410A-25"      },
  "DISC-60A":      { name: "60A Non-Fused Disconnect",           category: "Electrical",            unit: "ea", price: 32,    supplier: "Eaton",              sku: "DPU222R"       },
  "WHIP-6FT":      { name: "3/4\" Conduit Whip (6ft)",           category: "Electrical",            unit: "ea", price: 18,    supplier: "Southwire",          sku: "55189407"      },
  "BRKR-30A":      { name: "30A Dbl-Pole Breaker",               category: "Electrical",            unit: "ea", price: 12,    supplier: "Square D",           sku: "HOM230CP"      },
  "BRKR-40A":      { name: "40A Dbl-Pole Breaker",               category: "Electrical",            unit: "ea", price: 14,    supplier: "Square D",           sku: "HOM240CP"      },
  "BRKR-50A":      { name: "50A Dbl-Pole Breaker",               category: "Electrical",            unit: "ea", price: 16,    supplier: "Square D",           sku: "HOM250CP"      },
  "CPUMP":         { name: "Condensate Pump",                    category: "Installation",          unit: "ea", price: 65,    supplier: "Little Giant",       sku: "554405"        },
  "PTRAP":         { name: "P-Trap (3/4\" PVC)",                 category: "Installation",          unit: "ea", price: 4.50,  supplier: "Charlotte Pipe",     sku: "PVC00700"      },
  "DRAIN-PVC":     { name: "3/4\" PVC Drain Line (10ft)",        category: "Installation",          unit: "ea", price: 8.50,  supplier: "Charlotte Pipe",     sku: "PVC07010"      },
  "FILT-16x25":    { name: "16x25x1 Filter (MERV 8)",            category: "Installation",          unit: "ea", price: 6.50,  supplier: "Filtrete",           sku: "F16251"        },
  "FILT-20x25":    { name: "20x25x1 Filter (MERV 8)",            category: "Installation",          unit: "ea", price: 7.50,  supplier: "Filtrete",           sku: "F20251"        },
  "MASTIC":        { name: "Duct Mastic (1 Gal)",                category: "Installation",          unit: "ea", price: 14.50, supplier: "Hardcast",           sku: "304133"        },
  "TAPE-FOIL":     { name: "Foil Tape (2.5\"x60yd)",             category: "Installation",          unit: "ea", price: 12.50, supplier: "Nashua",             sku: "322"           },
  "PAD-COND":      { name: "Condenser Pad (24x24x3)",            category: "Installation",          unit: "ea", price: 38,    supplier: "DiversiTech",        sku: "EL2424-3"      },
  "HANGER":        { name: "Hanger Strap (100ft)",               category: "Installation",          unit: "ea", price: 22,    supplier: "Oatey",              sku: "33528"         },
};
